---

- hosts: all
  become: true
  tasks:

  - name: Install sample packages in both Ubuntu and CentOS at the same time
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Start Apache services
    service:
      name: httpd
      state: started

