---

- hosts: all
  become: true
  tasks:

          - name: Update repository index
            apt:
                    update_cache: yes

          - name: Install apache2 package
            apt:
                    name: apache2
                    state: latest

          - name: Install php modules for apache
            apt:
                    name: libapache2-mod-php7.4
                    state: latest

          - name: Start apache web server service
            service:
                    name: apache2
                    state: started
